export CONFLUENT_API_KEY=
export CONFLUENT_API_SECRET=
export CONFLUENT_BILLING_URL=
#List format [xxx,aaa]
export CONFLUENT_CLUSTER_LIST=[]
export CONFLUENT_SERVICE_ACCOUNT_URL=
export CONFLUENT_TELEMETRY_URL=
export NR_ACCOUNT_ID=
export NR_CUSTOM_EVENT_API_URL=
export NR_LICENSE_API_KEY=
